#!/usr/bin/env node
/**
 * botscaffold — quickly scaffold Telegram and/or Discord bots.
 *
 * Usage:
 *   node src/botscaffold.js create --platform telegram --name mybot
 *   node src/botscaffold.js create --platform discord --name mybot
 *   node src/botscaffold.js create --platform both --name mybot
 *   node src/botscaffold.js list
 */

const fs = require('fs');
const path = require('path');

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith('--')) {
      const [k, v] = a.slice(2).split('=');
      args[k] = v === undefined ? argv[++i] : v;
    }
  }
  return args;
}

function writeFile(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
}

const TELEGRAM_BOT = (name) => `#!/usr/bin/env node
/**
 * ${name} — Telegram bot generated by botscaffold.
 * Requires: npm install node-telegram-bot-api (or use as-is with fetch-based polling below).
 * Set TELEGRAM_BOT_TOKEN in your environment before running.
 */
const TOKEN = process.env.TELEGRAM_BOT_TOKEN;
if (!TOKEN) {
  console.error('Set TELEGRAM_BOT_TOKEN before starting the bot.');
  process.exit(1);
}

const API = \`https://api.telegram.org/bot\${TOKEN}\`;
let offset = 0;

async function getUpdates() {
  const res = await fetch(\`\${API}/getUpdates?offset=\${offset}&timeout=20\`);
  const data = await res.json();
  return data.result || [];
}

async function sendMessage(chatId, text) {
  await fetch(\`\${API}/sendMessage\`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ chat_id: chatId, text }),
  });
}

async function handleUpdate(update) {
  const msg = update.message;
  if (!msg || !msg.text) return;
  const text = msg.text.trim();

  if (text === '/start') {
    await sendMessage(msg.chat.id, 'Hi! I am ${name}, scaffolded by botscaffold. Try /help.');
  } else if (text === '/help') {
    await sendMessage(msg.chat.id, 'Commands:\\n/start - greet\\n/help - this message\\n/echo <text> - echo it back');
  } else if (text.startsWith('/echo ')) {
    await sendMessage(msg.chat.id, text.slice(6));
  } else {
    await sendMessage(msg.chat.id, \`You said: \${text}\`);
  }
}

async function loop() {
  console.log('${name} (Telegram) polling for updates... Ctrl+C to stop.');
  while (true) {
    try {
      const updates = await getUpdates();
      for (const u of updates) {
        offset = u.update_id + 1;
        await handleUpdate(u);
      }
    } catch (err) {
      console.error('Polling error:', err.message);
      await new Promise((r) => setTimeout(r, 2000));
    }
  }
}

if (require.main === module) loop();
module.exports = { handleUpdate };
`;

const DISCORD_BOT = (name) => `#!/usr/bin/env node
/**
 * ${name} — Discord bot generated by botscaffold.
 * Requires: npm install discord.js
 * Set DISCORD_BOT_TOKEN in your environment before running.
 */
const TOKEN = process.env.DISCORD_BOT_TOKEN;
if (!TOKEN) {
  console.error('Set DISCORD_BOT_TOKEN before starting the bot.');
  process.exit(1);
}

let Client, GatewayIntentBits;
try {
  ({ Client, GatewayIntentBits } = require('discord.js'));
} catch {
  console.error('discord.js is not installed. Run: npm install discord.js');
  process.exit(1);
}

const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent] });

client.once('ready', () => {
  console.log(\`${name} (Discord) logged in as \${client.user.tag}\`);
});

client.on('messageCreate', async (message) => {
  if (message.author.bot) return;
  const text = message.content.trim();

  if (text === '!ping') {
    await message.reply('pong 🏓');
  } else if (text === '!help') {
    await message.reply('Commands: !ping, !help, !echo <text>');
  } else if (text.startsWith('!echo ')) {
    await message.reply(text.slice(6));
  }
});

client.login(TOKEN);
`;

const README_SNIPPET = (name, platform) => `# ${name}

Generated by [botscaffold](https://github.com/) for **${platform}**.

## Setup

\`\`\`bash
npm install
export ${platform === 'telegram' ? 'TELEGRAM_BOT_TOKEN' : 'DISCORD_BOT_TOKEN'}=your-token-here
node ${platform}.js
\`\`\`
`;

function scaffold(platform, name) {
  const outDir = path.join(process.cwd(), 'bots', name, platform);

  if (platform === 'telegram') {
    writeFile(path.join(outDir, 'telegram.js'), TELEGRAM_BOT(name));
  } else if (platform === 'discord') {
    writeFile(path.join(outDir, 'discord.js'), DISCORD_BOT(name));
  } else {
    throw new Error(`Unknown platform: ${platform}`);
  }
  writeFile(path.join(outDir, 'README.md'), README_SNIPPET(name, platform));
  writeFile(path.join(outDir, 'package.json'), JSON.stringify({
    name: `${name}-${platform}-bot`,
    version: '1.0.0',
    private: true,
    scripts: { start: `node ${platform}.js` },
    dependencies: platform === 'discord' ? { 'discord.js': '^14.0.0' } : {},
  }, null, 2));

  return outDir;
}

function cmdCreate(args) {
  const name = args.name || 'mybot';
  const platform = args.platform || 'telegram';
  const platforms = platform === 'both' ? ['telegram', 'discord'] : [platform];

  console.log(`\n🤖 botscaffold — creating "${name}" for: ${platforms.join(', ')}\n`);
  for (const p of platforms) {
    const dir = scaffold(p, name);
    console.log(`✔ Created ${p} bot at ${path.relative(process.cwd(), dir)}/`);
  }
  console.log(`\nNext steps:\n  cd bots/${name}/${platforms[0]}\n  npm install\n  set your bot token env var\n  npm start\n`);
}

function cmdList() {
  console.log('Supported platforms: telegram, discord, both');
}

function main() {
  const [, , cmd, ...rest] = process.argv;
  const args = parseArgs(rest);

  if (cmd === 'create') return cmdCreate(args);
  if (cmd === 'list') return cmdList();

  console.log('botscaffold — scaffold Telegram/Discord bots\n');
  console.log('Usage:');
  console.log('  create --platform telegram --name mybot');
  console.log('  create --platform discord --name mybot');
  console.log('  create --platform both --name mybot');
  console.log('  list');
}

if (require.main === module) main();
module.exports = { scaffold };
